### ISSUE TITLE
posting here is a waste of time; maintainer is a troll

### ISSUE THREAD

**Issue by anewuser** [andymckay/new-arewee10syet.com#3]
-

**Comment by andymckay** [comment]
We are currently focusing on addons with over 100,000 users. Is there a reason you want to add this add-on?

**Comment by anewuser** [comment]
* It is the only way _on any current browser_ for you to have private tabs along with regular tabs in the same window. This makes users stick with Firefox instead of migrating to an alternative browser. 
* It's been featured on the official add-ons site and has about 70 000 users, with the potential of becoming much more popular since it's a unique feature.
* Its developer has been working hard to keep up with all the changes Firefox has been going through, but he needs some support back from Mozilla to make everything work: [issue tracker](https://github.com/Infocatcher/Private_Tab/issues?utf8=%E2%9C%93&q=is%3Aopen%20%5Be10s%5D).
* It has a [well-documented API](https://github.com/Infocatcher/Private_Tab/blob/master/README.md) used by other extensions, such as [Proxy Privacy Ruler](https://addons.mozilla.org/firefox/addon/proxy-privacy-ruler/) and [Auto Private](https://addons.mozilla.org/en-US/firefox/addon/auto-private/).

**Comment by andymckay** [comment]
Sure, but what does that have to do with being on arewee10syet?

**Comment by anewuser** [comment]
>Sure, but what does that have to do with being on arewee10syet?

Did you even click on my links or read anything I've typed so far?

1.  In the first post I left a link to the bug report about e10s breaking this extension.
2. You asked me why this extension should be added even though it has fewer than 100 thousand users
3. I provided a number of reasons and left a link to more bug reports on Github about e10s breaking it
4. Now you ask me "what this have to do with being on arewee10syet

This is surreal.

**Comment by andymckay** [comment]
Maintainer is not a troll, but I'm curious what the point of being on this site is for the add-on in question? Will it get more attention? Will it get updated by the author? Is there something you are expecting to happen that I am not fulfilling?

Please send a pull request with the addon if you want to the `data.json` file in the repo.

**Comment by andymckay** [comment]
Hmm data in comments got deleted.
